version: '3'

networks:
  default:
    name: ${netnovus_NETWORK:-netnovus-network}

services:
  akounting_nginx:
    image: nginx:stable-alpine
    container_name: akounting_nginx
    
    tty: true 
    labels: 
        - "traefik.frontend.rule=Host: 
            ${AKOUNTING:-akounting}.${TOP_DOMAIN:-local.netnovus.com}"
    volumes:
      - ./:/var/www
      - ./default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php_akounting
    
    networks:
      - default



  php_akounting:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: php_akounting
    tty: true   
    volumes:
      - ./:/var/www
  
    networks:
      - default

 